spring:
  application:
    name: top-link-mall
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 48080
sa-token:
  is-log: true
  token-style: tik
  is-share: false
  # Token validity period (unit: seconds) is set to 7 days
  timeout: 604800
  # Token minimum activity frequency (unit: seconds).
  # If there is no access for more than this period of time, it will be frozen. Set it to 1 hour.
  active-timeout: 3600
  # Is it allowed for the same account to log in simultaneously from multiple locations?
  is-concurrent: false
  token-name: tikToken